development:
  adapter: postgresql
  encoding: unicode
  database: gibipp_development
  pool: 5
  username: postgres
  password: enter

test:
  adapter: postgresql
  encoding: unicode
  database: gibipp_test
  pool: 5
  username: postgres
  password: enter